
INSERT INTO public.gigs (creator_id, title, company, company_verified, company_rating, company_review_count, budget, budget_value, duration, location, difficulty, category, description, full_description, requirements, deliverables, technologies, proposals_count, is_urgent, featured, client_member_since, client_total_spent, client_hire_rate, client_open_jobs)
VALUES
  ('00000000-0000-0000-0000-000000000000', 'Full-Stack Developer for E-commerce Platform', 'TechCorp Solutions', true, 4.8, 127, '$5,000 - $10,000', 7500, '2-3 months', 'Remote', 'Expert', 'Development', 'We''re looking for an experienced full-stack developer to help build and scale our e-commerce platform.', 'We are seeking a highly skilled full-stack developer to join our team and build a comprehensive e-commerce platform from the ground up. This is a greenfield project with significant creative freedom.

The platform will serve thousands of merchants and needs to be built with scalability, performance, and security as top priorities.', ARRAY['5+ years of experience with React and Node.js','Strong knowledge of PostgreSQL and database design','Experience with AWS services (EC2, S3, RDS, CloudFront)','TypeScript proficiency required','Experience building e-commerce or marketplace platforms preferred','Familiarity with payment gateway integration (Stripe)','Understanding of SEO best practices'], ARRAY['Complete e-commerce platform with product catalog, cart, and checkout','Admin dashboard for merchant management','Payment integration with Stripe','Mobile-responsive design across all pages','API documentation and deployment guide','30 days post-launch support'], ARRAY['React','Node.js','PostgreSQL','TypeScript','AWS'], 12, true, true, '2021', '$145,000+', 92, 3),

  ('00000000-0000-0000-0000-000000000000', 'UI/UX Designer for Mobile App Redesign', 'FinanceFlow', true, 4.9, 89, '$25 - $40/hr', 3200, '1-2 months', 'Remote', 'Expert', 'Design', 'Seeking a talented UI/UX designer to redesign our mobile banking application.', 'We''re looking for a talented UI/UX designer to completely redesign our mobile banking application. The current app serves 50,000+ users and we need a fresh, modern look.', ARRAY['3+ years of mobile app design experience','Strong portfolio showcasing fintech or banking apps','Expert-level Figma skills','Experience with design systems','Understanding of accessibility standards (WCAG 2.1)'], ARRAY['User flow diagrams for all core features','High-fidelity mockups for iOS and Android','Interactive prototype for user testing','Complete design system with tokens and components','Handoff documentation for engineering'], ARRAY['Figma','UI Design','UX Research','Prototyping','Mobile Design'], 15, true, false, '2022', '$89,000+', 95, 2),

  ('00000000-0000-0000-0000-000000000000', 'DevOps Engineer - CI/CD Pipeline Setup', 'CloudScale Inc', true, 4.7, 45, '$3,000 - $5,000', 4000, '2-4 weeks', 'Remote', 'Expert', 'DevOps', 'Need a DevOps expert to set up our CI/CD pipelines using GitHub Actions, Docker, and Kubernetes.', 'We need a DevOps engineer to establish our CI/CD infrastructure from scratch. Our team of 8 engineers currently deploys manually and we need to automate everything.', ARRAY['3+ years DevOps experience','Strong Docker & Kubernetes skills','AWS certified preferred'], ARRAY['Fully automated CI/CD pipeline','Infrastructure as code with Terraform','Monitoring and alerting setup'], ARRAY['Docker','Kubernetes','AWS','GitHub Actions','Terraform'], 15, false, false, '2023', '$34,000+', 88, 1),

  ('00000000-0000-0000-0000-000000000000', 'Build Admin Dashboard with Charts', 'AnalyticsCo', true, 4.6, 32, '$2,500 - $4,000', 3250, '2-3 weeks', 'Remote', 'Intermediate', 'Development', 'Create an analytics dashboard with interactive charts and real-time data visualization.', 'We need an experienced React developer to build a comprehensive admin dashboard with interactive charts and real-time data visualization.', ARRAY['3+ years React experience','Experience with Recharts or similar','Tailwind CSS proficiency'], ARRAY['Responsive admin dashboard','10+ chart components','Real-time data updates','Dark mode support'], ARRAY['React','Recharts','Tailwind'], 6, false, false, '2022', '$52,000+', 90, 2),

  ('00000000-0000-0000-0000-000000000000', 'E-commerce Checkout Flow', 'ShopWave', false, 4.4, 18, '$1,800 - $3,000', 2400, '1-2 weeks', 'Remote', 'Entry level', 'Development', 'Design and implement a seamless checkout flow with Stripe integration.', 'We need a clean, conversion-optimized checkout flow built with React and Stripe.', ARRAY['React & TypeScript','Stripe integration experience','Mobile-first design approach'], ARRAY['Multi-step checkout flow','Stripe payment integration','Order confirmation emails'], ARRAY['React','Stripe','TypeScript'], 9, false, false, '2023', '$12,000+', 85, 1),

  ('00000000-0000-0000-0000-000000000000', 'Real-time Chat Feature', 'ConnectHub', true, 4.8, 56, '$3,500 - $5,500', 4500, '3-4 weeks', 'Remote', 'Expert', 'Development', 'Implement real-time messaging with presence indicators, typing status, and file sharing.', 'Build a full-featured real-time chat system using WebSockets and Supabase Realtime.', ARRAY['WebSocket experience','Supabase Realtime knowledge','React performance optimization'], ARRAY['Real-time messaging','File sharing up to 25MB','Presence & typing indicators','Message search'], ARRAY['WebSocket','React','Supabase'], 4, false, false, '2021', '$98,000+', 94, 4),

  ('00000000-0000-0000-0000-000000000000', 'Landing Page Redesign', 'BrandForge', false, 4.3, 11, '$1,200 - $2,000', 1600, '1 week', 'Remote', 'Entry level', 'Design', 'Redesign a SaaS landing page with modern animations and responsive design.', 'We need a modern, high-converting landing page for our SaaS product.', ARRAY['Strong design sense','Framer Motion experience','Responsive design skills'], ARRAY['Fully responsive landing page','Scroll-triggered animations','SEO-optimized markup'], ARRAY['React','Framer Motion','Tailwind'], 18, false, false, '2024', '$3,500+', 80, 1),

  ('00000000-0000-0000-0000-000000000000', 'Junior Python Developer for Data Scripts', 'DataDriven Labs', false, 4.5, 23, '$25 - $40/hr', 1600, 'Ongoing', 'Remote', 'Entry level', 'Development', 'Looking for a junior Python developer to help write data processing scripts.', 'We need help writing and maintaining data processing scripts using Python, Pandas, and NumPy.', ARRAY['Basic Python knowledge','Familiarity with Pandas','SQL basics'], ARRAY['Data processing scripts','Documentation','Unit tests'], ARRAY['Python','Pandas','NumPy','SQL'], 28, false, false, '2023', '$15,000+', 82, 2),

  ('00000000-0000-0000-0000-000000000000', 'Smart Contract Developer - DeFi Protocol', 'CryptoVentures', true, 4.6, 34, '$15,000 - $25,000', 20000, '1-2 months', 'Remote', 'Expert', 'Blockchain', 'We need an experienced Solidity developer to audit and improve our DeFi protocol smart contracts.', 'We are building a next-generation DeFi protocol and need a seasoned Solidity developer.', ARRAY['3+ years Solidity experience','Security auditing skills','DeFi protocol knowledge','Hardhat/Foundry proficiency'], ARRAY['Security audit report','Optimized smart contracts','Test suite with 95%+ coverage','Deployment scripts'], ARRAY['Solidity','Web3.js','Hardhat','Security Auditing','DeFi'], 6, true, false, '2022', '$200,000+', 90, 3);
